language: java
services:
  - docker

script:
  - ./gradlew build

before_deploy:
  - docker build -t laterality/myblog:${DOCKER_IMAGE_VERSION} .

deploy:
  provider: script
  script: bash docker_push

branches:
  only:
    - master
    - develop