language: java
services:
  - docker

script:
  - ./gradlew build

before_deploy:
  - docker build -t laterality/myblog .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: feat/travis-integration